from fastapi import APIRouter, HTTPException, status
from fastapi.responses import StreamingResponse
from app.schemas.chat import ChatRequest, ChatResponse
from app.services.gemini import gemini_service

router = APIRouter()

@router.post(
    "/chat", 
    response_model=ChatResponse, 
    status_code=status.HTTP_200_OK,
    summary="Send a chat message to Gemini"
)
def chat_completion(request: ChatRequest):
    """
    Main chat route:
    - Validates request body using Pydantic `ChatRequest`
    - Delegates to `gemini_service`
    - Returns structured JSON response
    """
    try:
        return gemini_service.generate_chat(request)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Gemini API generation failed: {str(e)}"
        )

@router.post(
    "/chat/stream",
    summary="Stream chat response token-by-token"
)
def chat_stream(request: ChatRequest):
    """
    Streaming chat route:
    - Streams tokens as they are generated by Gemini.
    - Ideal for web & mobile interfaces for zero latency waiting.
    """
    try:
        return StreamingResponse(
            gemini_service.generate_chat_stream(request),
            media_type="text/plain"
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Gemini streaming failed: {str(e)}"
        )
